### ISSUE TITLE
Problem with the docker-compose version

### ISSUE THREAD

**Issue by ovizii** [soudis/datencockpit-docker#4]
I "slightly" adapted the docker-compose.yml file but when trying the 

docker-compose build command I get this error:

```
docker-compose build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

```

Any advice? 

```
docker -v
Docker version 18.03.1-ce, build 9ee9f40
```

**Comment by soudis** [comment]
does your adapted docker-compose.yml file start with the version reference? like:

`version: '3'`

**Comment by ovizii** [comment]
sorry, my mistake I should have provided that info. 

```
version: '3'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - /home/ovi/docker/datencockpit/datencockpit-db:/var/lib/mysql
      - ./kdz_datencockpit.sql:/docker-entrypoint-initdb.d/kdz_datencockpit.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=kdz_datencockpit
      - MYSQL_USER=kdz_datencockpit
      - MYSQL_PASSWORD=secret
    logging:
      options:
        max-size: 50m

  datencockpit:
    build:
      context: .
      args:
        DATENCOCKPIT_SITENAME: "Datencockpit"
        DATENCOCKPIT_URL: "https://dsgvo.mydomain.tld"
        DATENCOCKPIT_EMERGENCY_CONTACT: "ovidiu@mydomain.tld"
        DATENCOCKPIT_DB_HOST: "db"
        DATENCOCKPIT_DB_NAME: "kdz_datencockpit"
        DATENCOCKPIT_DB_USER: "kdz_datencockpit"
        DATENCOCKPIT_DB_PASSWORD: "secret"
    restart: always
    volumes:
      - /home/ovi/docker/datencockpit/datencockpit-html:/var/www/html
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 80:80
    logging:
      options:
        max-size: 50m
```
