### ISSUE TITLE
Can you help with LocalSettings.php.template ?

### ISSUE THREAD

**Issue by ovizii** [soudis/datencockpit-docker#6]
The URLs are quite ugly by default containing index.php which results in something like sub.domain.tld/index.php/Datencockpit 

I have read https://www.mediawiki.org/wiki/Manual:Short_URL but I didn't fully understand how to change LocalSettings.php.template to get something prettier like sub.domain.tld/DSGVO/Datencockpit as the result.

Can you help out?

**Comment by krabina** [comment]
always change LocalSettings.php, not LocalSettings.php.template!

You can unomment 
https://github.com/krabina/Datencockpit/blob/master/wiki/LocalSettings.php#L143
but you have to have a correct .htaccess file prepared:
http://www.mediawiki.org/wiki/Manual:Short_URL/Apache

**Comment by ovizii** [comment]
Thanks, I'll give it a try. after copying LocalSettings.php.template to LocalSettings.php and editing it, do I simply trigger the build process again or do I need to remove/clean some caches for the new settings to be applied?

Also, any advice on how to get this working with HTTPS without any warnings about insecure components? Any variables or URLs to set? So far I only found this one to change: 

```
  datencockpit:
    build:
      context: .
      args:
        DATENCOCKPIT_SITENAME: "Datencockpit"
        DATENCOCKPIT_URL: "https://sub.domain.tld"

```

**Comment by soudis** [comment]
The build process creates the LocalSettings.php out of the template, so it will overwritte any changes you make manually => do not trigger it afterwards

About the HTTPS: Simply chaning the protocol from http to https is not sufficient. You would need to have a SSL Server Certificate in place. If your server is accessible to the internet you can use let's encrypt. There are 2 practical docker images that set up a nginx reverse proxy and automatically obtain and refresh let's encrypt certificates for any running docker containers with the right environment variables (VIRTUAL_HOST and LETSENCRYPT_HOST):

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

You can add the following section to the **services** section of your docker-compose.yml:

```
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
```

then change the **ports** part of the datencockpit service from:

```
    ports:
      - 80:80
```
to:

```
    ports:
      - 80
```

and add an **environment** part to the datencockpit service:

```
    environment:
      - VIRTUAL_HOST=sub.domain.tld
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sub.domain.tld
      - LETSENCRYPT_EMAIL=adminemail@example.com
```
and finally run 

```
docker-compose up -d
```
again. I have not tested this, so please search the web or the documentation of the 2 docker images if you run into any troubles.
